to_logical – JSON-Fortran
to_logical Subroutine
Jacob Williams
16 statements
Source File
private subroutine to_logical(json, p, val, name)
Change the json_value variable to a logical.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
logical(kind=LK), intent(in), optional :: val
if the value is also to be set (if not present, then .false. is used).
character(kind=CK, len=*), intent(in), optional :: name
if the name is also to be changed.
Calls
Called by
Source Code
    subroutine to_logical(json,p,val,name)
    implicit none
    class(json_core),intent(inout)               :: json
    type(json_value),pointer                     :: p
    logical(LK),intent(in),optional              :: val   !! if the value is also to be set
                                                          !! (if not present, then .false. is used).
    character(kind=CK,len=*),intent(in),optional :: name  !! if the name is also to be changed.
    !set type and value:
    call destroy_json_data(p)
    p%var_type = json_logical
    allocate(p%log_value)
    if (present(val)) then
        p%log_value = val
    else
        p%log_value = .false.    !default value
    end if
    !name:
    if (present(name)) call json%rename(p,name)
    end subroutine to_logical
Call graph
to_logical calls destroy_json_data
json_update_logical calls to_logical
json_value_create_logical calls to_logical
parse_value_nonrecursive calls to_logical
parse_value_recursive calls to_logical
json_add_logical_by_path calls create_logical
json_value_add_logical calls create_logical
wrap_json_value_create_logical calls create_logical
wrap_json_add_logical_by_path calls json_add_logical_by_path