to_string – JSON-Fortran
to_string Subroutine
Jacob Williams
37 statements
Source File
private subroutine to_string(json, p, val, name, trim_str, adjustl_str)
Change the json_value variable to a string.
Modified
Izaak Beekman : 02/24/2015
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
character(kind=CK, len=*), intent(in), optional :: val
if the value is also to be set (if not present, then ‘’ is used).
character(kind=CK, len=*), intent(in), optional :: name
if the name is also to be changed.
logical(kind=LK), intent(in), optional :: trim_str
if TRIM() should be called for the val (only used if val is present)
logical(kind=LK), intent(in), optional :: adjustl_str
if ADJUSTL() should be called for the val (only used if val is present) (note that ADJUSTL is done before TRIM)
Calls
Called by
Source Code
    subroutine to_string(json,p,val,name,trim_str,adjustl_str)
    implicit none
    class(json_core),intent(inout)  :: json
    type(json_value),pointer        :: p
    character(kind=CK,len=*),intent(in),optional :: val   !! if the value is also to be set
                                                          !! (if not present, then '' is used).
    character(kind=CK,len=*),intent(in),optional :: name  !! if the name is also to be changed.
    logical(LK),intent(in),optional     :: trim_str       !! if TRIM() should be called for the `val`
                                                          !! (only used if `val` is present)
    logical(LK),intent(in),optional     :: adjustl_str    !! if ADJUSTL() should be called for the `val`
                                                          !! (only used if `val` is present)
                                                          !! (note that ADJUSTL is done before TRIM)
    character(kind=CK,len=:),allocatable :: str !! temp string for `trim()` and/or `adjustl()`
    logical :: trim_string    !! if the string is to be trimmed
    logical :: adjustl_string !! if the string is to be adjusted left
    !set type and value:
    call destroy_json_data(p)
    p%var_type = json_string
    if (present(val)) then
        if (present(trim_str)) then
            trim_string = trim_str
        else
            trim_string = .false.
        end if
        if (present(adjustl_str)) then
            adjustl_string = adjustl_str
        else
            adjustl_string = .false.
        end if
        if (trim_string .or. adjustl_string) then
            str = val
            if (adjustl_string) str = adjustl(str)
            if (trim_string)    str = trim(str)
            p%str_value = str
        else
            p%str_value = val
        end if
    else
        p%str_value = CK_''  ! default value
    end if
    !name:
    if (present(name)) call json%rename(p,name)
    end subroutine to_string
Call graph
to_string calls destroy_json_data
json_update_string calls to_string, add_by_path
json_value_create_string calls to_string
parse_value_nonrecursive calls to_string
parse_value_recursive calls to_string
json_add_string_by_path calls create_string
json_value_add_string calls create_string
wrap_json_value_create_string calls create_string
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_update_integer calls add_by_path
json_update_logical calls add_by_path
json_update_real calls add_by_path
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec