to_unicode – JSON-Fortran
to_unicode Interface
3 statements
Source File
public interface to_unicode
Convert a ‘DEFAULT’ kind character input to ‘ISO_10646’ kind and return it
Calls
Called by
Module Procedures
private pure function to_uni(str)
Author
Izaak Beekman
Convert string to unicode (CDK to CK).
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: str
Return Value character(kind=CK, len=len)
private pure function to_uni_vec(str)
Author
Izaak Beekman
Convert array of strings to unicode (CDK to CK).
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in), dimension(:) :: str
Return Value character(kind=CK, len=len), dimension(size(str))
Call graph
to_unicode calls to_uni, to_uni_vec
default_comp_ucs4 calls to_unicode
default_join_ucs4 calls to_unicode
default_neq_ucs4 calls to_unicode
json_add_string_by_path_path_ascii calls to_unicode, json_add_string_by_path
json_add_string_by_path_value_ascii calls to_unicode, json_add_string_by_path
json_add_string_vec_by_path_path_ascii calls to_unicode, json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls to_unicode, json_add_string_vec_by_path
json_file_add_string_path_ascii calls to_unicode, create_object, json_file_add_string
json_file_add_string_value_ascii calls to_unicode, create_object, json_file_add_string
json_file_add_string_vec_path_ascii calls to_unicode, json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls to_unicode, json_file_add_string_vec
json_file_rename_name_ascii calls to_unicode
json_file_rename_path_ascii calls to_unicode
json_file_update_string_name_ascii calls to_unicode, update
json_file_update_string_val_ascii calls to_unicode, update
json_rename_by_path_name_ascii calls to_unicode
json_rename_by_path_path_ascii calls to_unicode
json_update_string_name_ascii calls to_unicode, update
json_update_string_val_ascii calls to_unicode, update
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
ucs4_comp_default calls to_unicode
ucs4_join_default calls to_unicode
ucs4_neq_default calls to_unicode
wrap_assign_string_to_json_file calls to_unicode, assign_string_to_json_file
wrap_initialize_json_file_from_string calls to_unicode, initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls to_unicode, initialize_json_file_from_string_v2
wrap_json_add_integer_by_path calls to_unicode, json_add_integer_by_path
wrap_json_add_integer_vec_by_path calls to_unicode, json_add_integer_vec_by_path
wrap_json_add_logical_by_path calls to_unicode, json_add_logical_by_path
wrap_json_add_logical_vec_by_path calls to_unicode, json_add_logical_vec_by_path
wrap_json_add_member_by_path calls to_unicode, json_add_member_by_path
wrap_json_add_null_by_path calls to_unicode, json_add_null_by_path
wrap_json_add_null_vec_by_path calls to_unicode, json_add_null_vec_by_path
wrap_json_add_real32_by_path calls to_unicode, add_by_path
wrap_json_add_real32_vec_by_path calls to_unicode, add_by_path
wrap_json_add_real_by_path calls to_unicode, json_add_real_by_path
wrap_json_add_real_vec_by_path calls to_unicode, json_add_real_vec_by_path
wrap_json_add_string_by_path calls to_unicode, json_add_string_by_path
wrap_json_add_string_vec_by_path calls to_unicode, json_add_string_vec_by_path
wrap_json_create_by_path calls to_unicode, create
wrap_json_file_add_integer calls to_unicode, json_file_add_integer
wrap_json_file_add_integer_vec calls to_unicode, json_file_add_integer_vec
wrap_json_file_add_logical calls to_unicode, json_file_add_logical
wrap_json_file_add_logical_vec calls to_unicode, json_file_add_logical_vec
wrap_json_file_add_null calls to_unicode, json_file_add_null
wrap_json_file_add_null_vec calls to_unicode, json_file_add_null_vec
wrap_json_file_add_object calls to_unicode, json_file_add_object
wrap_json_file_add_real calls to_unicode, json_file_add_real
wrap_json_file_add_real32 calls to_unicode, json_file_add_real32
wrap_json_file_add_real32_vec calls to_unicode, json_file_add_real32_vec
wrap_json_file_add_real_vec calls to_unicode, json_file_add_real_vec
wrap_json_file_add_string calls to_unicode, json_file_add_string
wrap_json_file_add_string_vec calls to_unicode, json_file_add_string_vec
wrap_json_file_get_alloc_string_vec calls to_unicode, get
wrap_json_file_get_integer calls to_unicode, get
wrap_json_file_get_integer_vec calls to_unicode, get
wrap_json_file_get_logical calls to_unicode, get
wrap_json_file_get_logical_vec calls to_unicode, get
wrap_json_file_get_object calls to_unicode, get
wrap_json_file_get_real calls to_unicode, get
wrap_json_file_get_real32 calls to_unicode, get
wrap_json_file_get_real32_vec calls to_unicode, get
wrap_json_file_get_real_vec calls to_unicode, get
wrap_json_file_get_string calls to_unicode, get
wrap_json_file_get_string_vec calls to_unicode, get
wrap_json_file_load_from_string calls to_unicode, deserialize
wrap_json_file_remove calls to_unicode, remove
wrap_json_file_rename calls to_unicode
wrap_json_file_update_integer calls to_unicode, update
wrap_json_file_update_logical calls to_unicode, update
wrap_json_file_update_real calls to_unicode, update
wrap_json_file_update_real32 calls to_unicode, update
wrap_json_file_update_string calls to_unicode, update
wrap_json_file_valid_path calls to_unicode, valid_path
wrap_json_file_valid_path_op calls to_unicode
wrap_json_file_variable_info calls to_unicode, info
wrap_json_file_variable_matrix_info calls to_unicode, matrix_info
wrap_json_get_alloc_string_vec_by_path calls to_unicode, get
wrap_json_get_array_by_path calls to_unicode, get
wrap_json_get_by_path calls to_unicode, get
wrap_json_get_integer_by_path calls to_unicode, get
wrap_json_get_integer_vec_by_path calls to_unicode, get
wrap_json_get_logical_by_path calls to_unicode, get
wrap_json_get_logical_vec_by_path calls to_unicode, get
wrap_json_get_path calls to_unicode, get_path
wrap_json_get_real32_by_path calls to_unicode, get
wrap_json_get_real32_vec_by_path calls to_unicode, get
wrap_json_get_real_by_path calls to_unicode, get
wrap_json_get_real_vec_by_path calls to_unicode, get
wrap_json_get_string_by_path calls to_unicode, get
wrap_json_get_string_vec_by_path calls to_unicode, get
wrap_json_info_by_path calls to_unicode, info
wrap_json_matrix_info_by_path calls to_unicode, matrix_info
wrap_json_parse_string calls to_unicode, deserialize
wrap_json_rename_by_path calls to_unicode
wrap_json_throw_exception calls to_unicode, throw_exception
wrap_json_update_integer calls to_unicode, update
wrap_json_update_logical calls to_unicode, update
wrap_json_update_real calls to_unicode, update
wrap_json_update_real32 calls to_unicode, update
wrap_json_update_string calls to_unicode, update
wrap_json_valid_path calls to_unicode, valid_path
wrap_json_value_add_integer calls to_unicode, add
wrap_json_value_add_integer_vec calls to_unicode, add
wrap_json_value_add_logical calls to_unicode, add
wrap_json_value_add_logical_vec calls to_unicode, add
wrap_json_value_add_null calls to_unicode, add
wrap_json_value_add_real calls to_unicode, add
wrap_json_value_add_real32 calls to_unicode, add
wrap_json_value_add_real32_vec calls to_unicode, add
wrap_json_value_add_real_vec calls to_unicode, add
wrap_json_value_add_string calls to_unicode, add
wrap_json_value_add_string_vec calls to_unicode, add
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_integer calls to_unicode, create_integer
wrap_json_value_create_logical calls to_unicode, create_logical
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
wrap_json_value_create_real calls to_unicode, create_real
wrap_json_value_create_real32 calls to_unicode, create_real
wrap_json_value_create_string calls to_unicode, create_string
wrap_json_value_get_child_by_name calls to_unicode, get
wrap_json_value_remove_if_present calls to_unicode, remove_if_present
wrap_json_value_rename calls to_unicode
json_file calls wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2, initialize_json_file_from_string, initialize_json_file_from_string_v2, initialize_json_file
operator(==) calls default_comp_ucs4, ucs4_comp_default
operator(SLASH=) calls default_neq_ucs4, ucs4_neq_default
operator(SLASHSLASH) calls default_join_ucs4, ucs4_join_default
assign_string_to_json_file calls deserialize
convert calls create_array, create_null, create_object, info, throw_exception, json_value_replace
initialize_json_file_from_string calls deserialize, initialize
initialize_json_file_from_string_v2 calls deserialize
json_add_integer_by_path calls create, create_integer, info, throw_exception, json_value_replace
json_add_integer_vec_by_path calls add, create, create_array, info, json_value_replace
json_add_logical_by_path calls create, create_logical, info, throw_exception, json_value_replace
json_add_logical_vec_by_path calls add, create, create_array, info, json_value_replace
json_add_member_by_path calls create, info, throw_exception, json_value_replace
json_add_null_by_path calls create, create_null, info, throw_exception, json_value_replace
json_add_null_vec_by_path calls add, create, create_array, info, json_value_replace
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_add_real_by_path calls create, create_real, info, throw_exception, json_value_replace
json_add_real_vec_by_path calls add, create, create_array, info, json_value_replace
json_add_string_by_path calls create, create_string, info, throw_exception, json_value_replace
json_add_string_vec_by_path calls add, create, create_array, info, throw_exception, json_value_replace
json_check_children_for_duplicate_keys calls get_child, get_path, throw_exception
json_count calls throw_exception
json_create_by_path calls throw_exception, json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_file_add_integer calls add_by_path, create_object
json_file_add_integer_vec calls add_by_path, create_object
json_file_add_logical calls add_by_path, create_object
json_file_add_logical_vec calls add_by_path, create_object
json_file_add_null calls add_null_by_path, create_object
json_file_add_null_vec calls add_null_by_path, create_object
json_file_add_object calls add_by_path, create_object
json_file_add_real calls add_by_path, create_object
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path, create_object
json_file_add_string calls add_by_path, create_object
json_file_add_string_vec calls add_by_path, create_object
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_file_load_from_string calls deserialize
json_file_move_pointer calls throw_exception, initialize
json_file_print_to_unit calls throw_exception
json_file_remove calls remove_if_present
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_real32 calls update
json_file_update_string calls update
json_file_valid_path calls valid_path
json_file_valid_path_op calls valid_path
json_file_variable_info calls info
json_file_variable_matrix_info calls matrix_info
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get, throw_exception
json_get_array calls throw_exception
json_get_array_by_path calls get, throw_exception
json_get_by_path calls throw_exception, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_by_path_default calls add, get_child, throw_exception
json_get_by_path_jsonpath_bracket calls add, get_child, throw_exception, convert
json_get_by_path_rfc6901 calls get_child, throw_exception
json_get_integer calls throw_exception
json_get_integer_by_path calls get, throw_exception
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get, throw_exception
json_get_logical calls throw_exception
json_get_logical_by_path calls get, throw_exception
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get, throw_exception
json_get_next calls throw_exception
json_get_parent calls throw_exception
json_get_path calls info, throw_exception
json_get_previous calls throw_exception
json_get_real calls throw_exception
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get, throw_exception
json_get_real_vec calls get
json_get_real_vec_by_path calls get, throw_exception
json_get_string calls throw_exception
json_get_string_by_path calls get, throw_exception
json_get_string_vec calls get
json_get_string_vec_by_path calls get, throw_exception
json_get_tail calls throw_exception
json_info calls throw_exception
json_info_by_path calls get, info
json_initialize calls throw_exception
json_is_vector calls info, throw_exception
json_matrix_info calls get_child, info, throw_exception
json_matrix_info_by_path calls get, matrix_info
json_parse_end calls throw_exception
json_parse_file calls throw_exception, json_initialize, json_parse_end, json_check_all_for_duplicate_keys
json_parse_string calls throw_exception, json_initialize, json_parse_end, json_check_all_for_duplicate_keys
json_print_to_filename calls throw_exception
json_print_to_unit calls throw_exception, json_value_print
json_rename_by_path calls get, throw_exception
json_string_info calls get, info, throw_exception
json_traverse calls throw_exception
json_update_integer calls add_by_path, get, info, throw_exception
json_update_logical calls add_by_path, get, info, throw_exception
json_update_real calls add_by_path, get, info, throw_exception
json_update_real32 calls update
json_update_string calls add_by_path, get, info, throw_exception
json_valid_path calls get
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls throw_exception
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_value_create_real32 calls create_real
json_value_equals calls get_child, json_value_equals
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception
json_value_get_child_by_name calls throw_exception
json_value_insert_after_child_by_index calls get_child, insert_after
json_value_print calls throw_exception, json_is_vector, json_value_print
json_value_remove_if_present calls get
json_value_reverse calls info
json_value_swap calls throw_exception, json_value_is_child_of
json_value_validate calls throw_exception, json_check_all_for_duplicate_keys
parse_array calls add, throw_exception
parse_for_chars calls throw_exception
parse_object calls add, throw_exception, parse_object, parse_string
parse_string calls throw_exception
parse_value_nonrecursive calls add, throw_exception, parse_for_chars, parse_string, push_char, parse_number
parse_value_recursive calls throw_exception, parse_array, parse_for_chars, parse_object, parse_string, push_char, parse_number
push_char calls throw_exception
string_to_dble calls throw_exception
string_to_int calls throw_exception
initialize_json_core calls json_initialize
initialize_json_core_in_file calls json_initialize
json_check_all_for_duplicate_keys calls json_traverse
json_file_traverse calls json_traverse
json_value_is_child_of calls json_traverse
json_value_to_string calls json_value_print
parse_number calls push_char, string_to_dble, string_to_int
json_core calls initialize_json_core
assign_json_file_to_string calls json_value_to_string
json_file_load calls load
json_file_print_to_string calls json_value_to_string
json_value_replace calls insert_after
initialize_json_file calls initialize